### PR TITLE
Add LICENSE.md as informed in Issue #11

### LINKED ISSUE #11: Add LICENSE to this repo
Add LICENSE.md file to the project, same like this

https://raw.githubusercontent.com/arshadkazmi42/custom-date-formatting/master/LICENSE

### PR DESCRIPTION
**Pull request by victorhmp**
Fixes #11

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Looks good. Can you add the issue number in the description something like this `#11`

**Comment by victorhmp** [comment]
Sure! Sorry, but how can I edit the pull request? (I'm new to this 😅)

Em sex, 12 de out de 2018 às 13:33, Arshad Kazmi <notifications@github.com>
escreveu:

**Comment by arshadkazmi42** [comment]
@victorhmp I will add it. It just needs to be added in a comment like this comment. Let me update your comment. You can take care of this from next PR onwards

**Comment by arshadkazmi42** [comment]
@victorhmp Congrats on your first PR. Thanks alot for working on this 👍

**Comment by victorhmp** [comment]
Thanks!! Happy to help :D

**Pull request merged**
